-- 관리자
CREATE TABLE ADMIN (
	ID VARCHAR(20) PRIMARY KEY
	, PASSWORD VARCHAR(20) NOT NULL
);

INSERT INTO 
	ADMIN
VALUES
	("root", "1234")
;

SELECT * FROM ADMIN;

-- 사용자
CREATE TABLE USERES (
	ID VARCHAR(20) PRIMARY KEY
	, PASSWORD VARCHAR(20) NOT NULL
	, NAME VARCHAR(20) NOT NULL
	, PHONE VARCHAR(11) NOT NULL
	, DATETIME_REGISTER TIMESTAMP DEFAULT NOW()
	, DELETEFLAG VARCHAR(1) default 'N'
);

select * from useres;

-- 청첩장 양식
CREATE TABLE INVITATION_FORM (
	FORMCODE VARCHAR(10) PRIMARY KEY
	, FORMNAME VARCHAR(10) NOT NULL
);

INSERT INTO
	INVITATION_FORM
VALUES
	("hookup", "hookup")
;

SELECT * FROM INVITATION_FORM;


-- 청첩장 목록
CREATE TABLE INVITATION_LIST (
	SEQ INT PRIMARY KEY AUTO_INCREMENT
	, ID VARCHAR(20) NOT NULL
	, NAME VARCHAR(20) NOT NULL
	, VISIBLE VARCHAR(1) DEFAULT 'N'
	, DATE_BEGIN VARCHAR(8) NOT NULL
	, DATE_END VARCHAR(8) NOT NULL
	, FORMCODE VARCHAR(10) NOT null
	, USE_EACH_IMAGE VARCHAR(1)
	, USE_LS VARCHAR(1)
	, USE_PYEBAEK VARCHAR(1)
	, USE_G VARCHAR(1)
	, USE_SM VARCHAR(1)
	, DATETIME_REGISTER TIMESTAMP DEFAULT NOW()
	, DATETIME_UPDATE TIMESTAMP DEFAULT NOW()
	, FOREIGN KEY (ID) REFERENCES USERES (ID)
	, FOREIGN KEY (FORMCODE) REFERENCES INVITATION_FORM (FORMCODE)
);
DROP TABLE invitation_list;

SELECT * FROM INVITATION_LIST;

-- 청첩장 카테고리 분류 (첨부파일이 있는)
CREATE TABLE CATEGORY (
	CODE VARCHAR(5) PRIMARY KEY
	, NAME VARCHAR(15) NOT NULL
);

INSERT INTO
	CATEGORY
VALUES
	-- ("MI", "메인 및 기본 정보")
	-- ("LS", "LOVE STORY")
	-- ("G", "GALLERY")
;

SELECT * FROM CATEGORY;


-- 첨부파일 모음
-- 첨부파일(이미지, 썸네일) 싸그리 모으는 테이블로 하고 각 메뉴 테이블 컬럼에 첨부파일명 같이 넣어주기
CREATE TABLE ATTACH (
	SEQ INT PRIMARY KEY AUTO_INCREMENT
	, FULLNAME VARCHAR(150)
	, CATEGORY VARCHAR(5)
	, CATEGORY_SEQ INT
	, DATETIME_REGISTER TIMESTAMP DEFAULT NOW()
	, FOREIGN KEY (CATEGORY) REFERENCES CATEGORY(CODE)
);

SELECT * FROM ATTACH;

-- 메인 및 기본 정보 
CREATE TABLE MAIN_INFO (
	SEQ INT PRIMARY KEY AUTO_INCREMENT
	, INV_SEQ INT NOT NULL
	, ID VARCHAR(20) NOT NULL
	, DATE_WEDDING VARCHAR(8) NOT NULL
	, TIME_WEDDING VARCHAR(4) NOT NULL
	, X_PLACE VARCHAR(30) NOT NULL
	, Y_PLACE VARCHAR(30) NOT NULL
	, ADDRESS VARCHAR(100) NOT NULL
	, CONTENT_GROOM VARCHAR(1000) NOT NULL
	, CONTENT_BRIDE VARCHAR(1000) NOT NULL
	, SEQ_IMAGE_MAIN INT
	, FULLNAME_MAIN VARCHAR(150)
	, YN_EACH_IMGAGE VARCHAR(1) DEFAULT 'N'
	, SEQ_IMAGE_GROOM INT
	, FULLNAME_GROOM VARCHAR(150)
	, SEQ_IMAGE_BRIDE INT
	, FULLNAME_BRIDE VARCHAR(150)
	, DATETIME_REGISTER TIMESTAMP DEFAULT NOW()
	, DATETIME_UPDATE TIMESTAMP DEFAULT NOW()
	, FOREIGN KEY (INV_SEQ) REFERENCES INVITATION_LIST (SEQ)
	, FOREIGN KEY (ID) REFERENCES USERES (ID)
);
DROP TABLE main_info;

SELECT * FROM MAIN_INFO;


-- LOVE STORY
CREATE TABLE LOVE_STORY (
	SEQ INT PRIMARY KEY AUTO_INCREMENT
	, INV_SEQ INT NOT NULL
	, ID VARCHAR(20) NOT NULL
	, IS_DELETE BOOLEAN
	, DATE_STORY VARCHAR(8) NOT NULL
	, TITLE VARCHAR(20) NOT NULL
	, CONTENT VARCHAR(200) NOT NULL
	, SEQ_IMAGE INT
	, FULLNAME VARCHAR(150)
	, DATETIME_REGISTER TIMESTAMP DEFAULT NOW()
	, DATETIME_UPDATE TIMESTAMP DEFAULT NOW()
	, FOREIGN KEY (INV_SEQ) REFERENCES INVITATION_LIST (SEQ)
	, FOREIGN KEY (ID) REFERENCES USERES (ID)
);
DROP TABLE love_story;

SELECT * FROM LOVE_STORY;

-- WHEN WHERE
CREATE TABLE WHEN_WHERE (
	SEQ INT PRIMARY KEY AUTO_INCREMENT
	, INV_SEQ INT NOT NULL
	, ID VARCHAR(20) NOT NULL
	, IS_PYEBAEK BOOLEAN
	, DATE_WW VARCHAR(8) NOT NULL
	, TIME_WW VARCHAR(4) NOT NULL
	, X_PLACE VARCHAR(30) NOT NULL
	, Y_PLACE VARCHAR(30) NOT NULL
	, ADDRESS VARCHAR(100) NOT NULL
	, TITLE VARCHAR(20) NOT NULL
	, CONTENT VARCHAR(100) NOT null
	, DATETIME_REGISTER TIMESTAMP DEFAULT NOW()
	, DATETIME_UPDATE TIMESTAMP DEFAULT NOW()
	, FOREIGN KEY (INV_SEQ) REFERENCES INVITATION_LIST (SEQ)
	, FOREIGN KEY (ID) REFERENCES USERES (ID)
);
DROP TABLE when_where;

SELECT * FROM WHEN_WHERE;

-- GALLERY
CREATE TABLE GALLERY (
	SEQ INT PRIMARY KEY AUTO_INCREMENT
	, INV_SEQ INT NOT NULL
	, ID VARCHAR(20) NOT NULL
	, IS_DELETE BOOLEAN
	, SEQ_IMAGE INT
	, FULLNAME VARCHAR(150)
	, DATETIME_REGISTER TIMESTAMP DEFAULT NOW()
	, DATETIME_UPDATE TIMESTAMP DEFAULT NOW()
	, FOREIGN KEY (INV_SEQ) REFERENCES INVITATION_LIST (SEQ)
	, FOREIGN KEY (ID) REFERENCES USERES (ID)
);
DROP TABLE gallery;

SELECT * FROM GALLERY;

-- SWEET MESSAGE
CREATE TABLE SWEET_MESSAGE (
	SEQ INT PRIMARY KEY AUTO_INCREMENT
	, INV_SEQ INT NOT NULL
	, ID VARCHAR(20) NOT NULL
	, IS_DELETE BOOLEAN
	, REGISTER_NAME VARCHAR(20) NOT NULL
	, REGISTER_CONTENT VARCHAR(100) NOT NULL
	, REGISTER_PASSWORD VARCHAR(20) NOT null
	, DATETIME_REGISTER TIMESTAMP DEFAULT NOW()
	, DATETIME_UPDATE TIMESTAMP DEFAULT NOW()
	, FOREIGN KEY (INV_SEQ) REFERENCES INVITATION_LIST (SEQ)
	, FOREIGN KEY (ID) REFERENCES USERES (ID)
);
DROP TABLE sweet_message;

SELECT * FROM SWEET_MESSAGE;

select host, user, password from mysql.user;
show grants for 'root'@'%';
create user 'invitation'@'localhost' identified by '1111';
grant all privileges on INVITATION.* to 'invitation'@'localhost';